# Generated by Django 5.0.6 on 2024-06-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_first_name_user_last_name_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
